name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install flake8 flake8-import-order
    - name: Flake8
      run: flake8 --ignore=E501 config.py app
